CREATE TABLE USER_INFO (
    id int,
    username varchar(30),
    name varchar(60),
    email varchar(255),
    password varchar(255),
    roles varchar(30),
    primary key (id)
);
CREATE TABLE STOCK (
    item_id int,
    item_name varchar(30),
    item_price float,
    qty FLOAT,
    primary key (item_id)
);
CREATE TABLE SHOPPING_CART(
    USERNAME VARCHAR(30) NOT NULL,
    ITEM_ID INT NOT NULL,
    QTY FLOAT NOT NULL,
    PRIMARY KEY (USERNAME, ITEM_ID)
);
CREATE TABLE MASTER_TRANSACTION(
    ID INT NOT NULL,
    TRANSACTION_TIME TIMESTAMP NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    GRAND_TOTAL FLOAT,
    PRIMARY KEY(ID)
);

CREATE TABLE TRANSACTION_DETAIL(
    ID INT NOT NULL,
    ITEM_ID INT NOT NULL,
    QTY FLOAT NOT NULL,
    TOTAL_PRICE FLOAT NOT NULL,
    PRIMARY KEY(ID, ITEM_ID)
);

CREATE SEQUENCE STOCK_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE USER_INFO_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE MASTER_TRANSACTION_SEQUENCE
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE;

-- UNTUK RESTART
ALTER SEQUENCE STOCK_SEQUENCE RESTART WITH 1;
ALTER SEQUENCE USER_INFO_SEQUENCE RESTART WITH 1;
ALTER SEQUENCE MASTER_TRANSACTION_SEQUENCE RESTART WITH 1;